### ISSUE TITLE
 QRCode.draw is not a function

### ISSUE THREAD

**Issue by Mobilpadde** [heartnetkung/node-fancy-qr#1]
I'm getting this error, which I have no idea how to fix. 

`TypeError: QRCode.draw is not a function`

Attached a screenshot below:

![screenshot from 2018-08-24 04 40 48](https://user-images.githubusercontent.com/1170567/44562058-09e89c00-a758-11e8-9d45-6fda02fa8693.png)

**Comment by heartnetkung** [comment]
`QRCode` is a library which requires native dependency. Make sure you install it properly as instructed here https://github.com/Automattic/node-canvas/wiki

**Comment by Mobilpadde** [comment]
Nop, I'm not sure. But I found another lib, which does the job, sorry for any inconvenience!

**Comment by basit1327** [comment]
same problem with me QRCode.draw is not a function
Mobilpadde which lib you found

**Comment by Mobilpadde** [comment]
@basit1327 this lil' gem, https://www.npmjs.com/package/qrcode.es :+1:

**Comment by basit1327** [comment]
@Mobilpadde thanks for sharing this lib 
but iam searching for server based lib for nodejs have you any suggestion for this

**Comment by xellDart** [comment]
some here, im using nodejs
