### ISSUE TITLE
node-fancy modules

### ISSUE THREAD

**Issue by ijustesting123** [heartnetkung/node-fancy-qr#2]
Hi..
Can you update node-fancy modules? 
![index](https://user-images.githubusercontent.com/48037531/64157581-85038880-ce69-11e9-91df-636ef381fc72.jpeg)

**Comment by heartnetkung** [comment]
It seems you haven't installed the native dependency.
https://github.com/heartnetkung/node-fancy-qr/issues/1#issuecomment-415652419
